version: '3.1'

services:
  express:
    build: ./api-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3000:3000

  proxy:
    build: ./proxy
    restart: always
    ports:
     - 80:80
    volumes:
     - ./static/public:/var/www/public
     - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    command: /bin/bash -c '/usr/sbin/nginx -g "daemon off;"'

