version: '3.1'

services:
  express:
    build: ./express
    restart: always
    ports:
      - 8080:3000
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

