version: '3.1'

services:
    db:
        image: mongo
        restart: always
        enviroment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    cms:
        image: krappies/keystonejs-docker
        PORT: 80:80
        links: "mongo:mongo"
        ENV: .env


