# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
      #    working_directory: ~/repo
      #    working_directory: ~/api-server
    working_directory: ~/2018.perform/
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
        name: install packages
        #working_directory: ~/2018.perform/api-server
        command: cd api-server && yarn && yarn install && ls
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    working_directory: ~/2018.perform/
        #    working_directory: ~/api-server
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "api-server/package.json" }}
          - v1-dependencies-
      - run: 
          name: test express server
          working_directory: ~/2018.perform/api-server
          command: yarn test

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test
