# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
      #    working_directory: ~/repo
      #    working_directory: ~/api-server
    working_directory: ~/2018.perform/
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "ea:e4:cb:f7:2c:99:67:fe:0a:e6:5f:f6:65:0e:24:69"
      - run: 
          name: install packages
          command: |
              ssh-keyscan ${HOSTNAME} >> ~/.ssh/known_hosts
              cd api-server && yarn && yarn install && yarn test
      - deploy:
          name: deploy develop branch
          command: |
              echo ${CIRCLE_BRANCH},${USER_NAME},${DEPLOY_SERVER}
              if [ "${CIRCLE_BRANCH}" != "master" ]; then
                rsync -av --delete ./${USER_NAME}@${HOSTNAME}:/home/kfes/2018.perform
              fi
  test:
    working_directory: ~/2018.perform/
        #    working_directory: ~/api-server
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "api-server/package.json" }}
          - v1-dependencies-
      - run: 
          name: test express server
          working_directory: ~/2018.perform/api-server
          command: yarn test
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
