# Header
menu:
  Booth/Lab: /mogi-shop
  Event: /event
  Gallery: /gallery
  Map: /map
  Access: /access
  LINE@: /lineat
  

excerpt_link: Read More
fancybox: true

index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: 'UA-121910998-7'
gauges_analytics:
favicon: /img/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

#footer
footerLink:
  東京高専公式HP: "https://www.tokyo-ct.ac.jp/"
  東京高専後援会: "https://tokyo-ct-s.jp/"
  東京高専Twitter: "https://twitter.com/"
