# Header
menu:
  #Home: /
  #About: /about
  Booth: /mogi-shop
  Event: /event
  Gallery: /gallery
  Map: /map
  Access: /access
  LINE@: /lineat
  

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: 'UA-121910998-7'
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

#footer
footerLink:
  東京高専公式HP: "https://www.tokyo-ct.ac.jp/"
  東京高専後援会: "https://tokyo-ct-s.jp/"
  東京高専Twitter: "https://twitter.com/"
